name: Build ARMv7 for Raspi

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: elmaxiboy
          password: ${{ secrets.DOCKER_HUB_CREDS }}

      - name: Build and push ARMv7 Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm/v7
          push: true
          tags: elmaxiboy/npv_calculator:raspi

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Raspberry Pi via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.RASPBERRY_PI_HOST }}
          username: ${{ secrets.RASPBERRY_PI_USER }}
          key: ${{ secrets.RASPBERRY_PI_KEY }}
          script: |
            cd ~/energy
            docker-compose up -d
