name: Build ARMv7 for Raspi

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: elmaxiboy
          password: ${{ secrets.DOCKER_HUB_CREDS }}

      - name: Build and push ARMv7 Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm/v7
          push: true
          tags: elmaxiboy/npv_calculator:raspi
